name: Docker Build

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build Docker images (PR/test)
      if: github.event_name == 'pull_request'
      uses: docker/bake-action@v4
      with:
        files: |
          ./docker-bake.hcl
        targets: local
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max

    - name: Build and push Docker images
      if: github.event_name != 'pull_request'
      uses: docker/bake-action@v4
      with:
        files: |
          ./docker-bake.hcl
        targets: app
        push: true
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
          app.tags=${{ steps.meta.outputs.tags }}

    - name: Generate image summary
      if: github.event_name != 'pull_request'
      run: |
        echo "## Docker Images Built" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Platform | Tag |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-----|" >> $GITHUB_STEP_SUMMARY
        echo "| linux/amd64, linux/arm64 | \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\` |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Tags:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY